### ISSUE TITLE
Can't build with gradle

### ISSUE THREAD

**Issue by Czechball** [k0r0pt/tauro-core#7]
When I try to run "gradle build", I get the following errors:
```:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:checkstyleMain UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:checkstyleTest UP-TO-DATE
:test

 Test Suite: org.koreops.tauro.core.loggers.LoggerTest
Results: SUCCESS (7 tests, 7 successes, 0 failures, 0 skipped)


 Test Suite: org.koreops.tauro.core.db.DbConnEngineTest
Results: SUCCESS (2 tests, 2 successes, 0 failures, 0 skipped)


 Test Suite: org.koreops.tauro.core.constants.RouterAuthTypeTest
Results: SUCCESS (3 tests, 3 successes, 0 failures, 0 skipped)


 Test Suite: org.koreops.tauro.core.process.status.reporting.MailerTest
Results: SUCCESS (3 tests, 3 successes, 0 failures, 0 skipped)


org.koreops.tauro.core.process.ProcessManagerTest > testNonExistentDumpGetArgs FAILED
    org.junit.ComparisonFailure: expected:<...sources/process.ps ([No such file or directory])> but was:<...sources/process.ps ([Adresář nebo soubor neexistuje])>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.koreops.tauro.core.process.ProcessManagerTest.testNonExistentDumpGetArgs(ProcessManagerTest.java:87)

org.koreops.tauro.core.process.ProcessManagerTest > testNonExistentDumpGetCoveredHosts FAILED
    org.junit.ComparisonFailure: expected:<...sources/process.ps ([No such file or directory])> but was:<...sources/process.ps ([Adresář nebo soubor neexistuje])>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.koreops.tauro.core.process.ProcessManagerTest.testNonExistentDumpGetCoveredHosts(ProcessManagerTest.java:97)

 Test Suite: org.koreops.tauro.core.process.ProcessManagerTest
Results: FAILURE (4 tests, 2 successes, 2 failures, 0 skipped)


19 tests completed, 2 failed
:test FAILED

FAILURE: Build failed with an exception.

**Comment by sudiptosarkar** [comment]
@Czechball Please use `gradle build -DskipTests` for now.
The test cases are failing because the exception message we were testing for is coming in your language instead of English.

**Comment by Czechball** [comment]
Alright, I'll give it a try. Thanks

**Comment by Czechball** [comment]
I just ran `sudo gradle build -DskipTests` and got basically the same errors:
```czechball@Despacian:~/Cloned Repos/tauro-core$ sudo gradle build -DskipTests
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:checkstyleMain UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:checkstyleTest UP-TO-DATE
:test

 Test Suite: org.koreops.tauro.core.loggers.LoggerTest
Results: SUCCESS (7 tests, 7 successes, 0 failures, 0 skipped)


 Test Suite: org.koreops.tauro.core.db.DbConnEngineTest
Results: SUCCESS (2 tests, 2 successes, 0 failures, 0 skipped)


 Test Suite: org.koreops.tauro.core.constants.RouterAuthTypeTest
Results: SUCCESS (3 tests, 3 successes, 0 failures, 0 skipped)


 Test Suite: org.koreops.tauro.core.process.status.reporting.MailerTest
Results: SUCCESS (3 tests, 3 successes, 0 failures, 0 skipped)


org.koreops.tauro.core.process.ProcessManagerTest > testNonExistentDumpGetArgs FAILED
    org.junit.ComparisonFailure: expected:<...sources/process.ps ([No such file or directory])> but was:<...sources/process.ps ([Adresář nebo soubor neexistuje])>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.koreops.tauro.core.process.ProcessManagerTest.testNonExistentDumpGetArgs(ProcessManagerTest.java:87)

org.koreops.tauro.core.process.ProcessManagerTest > testNonExistentDumpGetCoveredHosts FAILED
    org.junit.ComparisonFailure: expected:<...sources/process.ps ([No such file or directory])> but was:<...sources/process.ps ([Adresář nebo soubor neexistuje])>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.koreops.tauro.core.process.ProcessManagerTest.testNonExistentDumpGetCoveredHosts(ProcessManagerTest.java:97)

 Test Suite: org.koreops.tauro.core.process.ProcessManagerTest
Results: FAILURE (4 tests, 2 successes, 2 failures, 0 skipped)


19 tests completed, 2 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/czechball/Cloned%20Repos/tauro-core/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.712 secs
```
Is there any other way to skip tests?

**Comment by sudiptosarkar** [comment]
@Czechball My bad... Use `gradle build -x test`

**Comment by Czechball** [comment]
This worked, thanks.
